{"uuid": "28eaa01d-b9a8-4771-9f3b-9e670c5322b5", "children": ["6a7ee78e-7735-4e9b-a263-60b4f5d7ff00"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.gemini.cloud.client' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Error executing adbExec. Original error: 'Command ''D:\\\\ruanjian\\\\android SDK\\\\platform-tools\\\\adb.exe' -P 5037 -s MBJVB20628004068 shell am start -W -n com.gemini.cloud.client/com.gemini.cloud.client.activity.AccountLoginActivity -S' exited with code 255'; Stderr: 'Security exception: Permission Denial: starting Intent { flg=0x10000000 cmp=com.gemini.cloud.client/.activity.AccountLoginActivity } from null (pid=13836, uid=2000) not exported from uid 10223\r\n\r\njava.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=com.gemini.cloud.client/.activity.AccountLoginActivity } from null (pid=13836, uid=2000) not exported from uid 10223\r\n\tat com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1192)\r\n\tat com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:906)\r\n\tat com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:654)\r\n\tat com.android.server.wm.HwActivityStarter.startActivity(HwActivityStarter.java:289)\r\n\tat com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1538)\r\n\tat com.android.server.wm.HwActivityStarter.startActivityMayWait(HwActivityStarter.java:524)\r\n\tat com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:585)\r\n\tat com.android.server.wm.ActivityTaskManagerService.startActivityAndWait(ActivityTaskManagerService.java:1334)\r\n\tat com.android.server.am.ActivityManagerService.startActivityAndWait(ActivityManagerService.java:3778)\r\n\tat com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:513)\r\n\tat com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:172)\r\n\tat android.os.ShellCommand.exec(ShellCommand.java:104)\r\n\tat com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10549)\r\n\tat android.os.Binder.shellCommand(Binder.java:888)\r\n\tat android.os.Binder.onTransact(Binder.java:772)\r\n\tat android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4536)\r\n\tat com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2951)\r\n\tat com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:374)\r\n\tat android.os.Binder.execTransactInternal(Binder.java:1028)\r\n\tat android.os.Binder.execTransact(Binder.java:1001)'; Code: '255'\n\n", "trace": "  File \"D:\\daima\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\daima\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\daima\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\appiumdm\\Appium_AutoTest\\testcase\\conftest.py\", line 38, in start_appium_desired\n    driver = appium_desired_caps(host, port)\n  File \"D:\\appiumdm\\Appium_AutoTest-Mobile\\base\\DesireCaps.py\", line 41, in appium_desired_caps\n    print(webdriver.Remote('http://%s:%s/wd/hub' % (host, port), desired_caps))\n  File \"D:\\daima\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 156, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\daima\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1618478649484, "stop": 1618478664852}], "start": 1618478649484, "stop": 1618478664917}