{"uuid": "96be7ebf-1181-480a-98ba-331c67599667", "children": ["d1cf9977-a63e-409a-90fe-e684c9bc5059"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.dayhr' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'com.dayhr' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Activity name '.com.dayhr/.login.activity.LoginActivity' used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity\n\n", "trace": "  File \"D:\\daima\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\daima\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\daima\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Appium_AutoTest-Mobile\\testcase\\conftest.py\", line 45, in start_appium_desired\n    driver = appium_desired_caps(host, port)\n  File \"D:\\Appium_AutoTest-Mobile\\base\\DesireCaps.py\", line 43, in appium_desired_caps\n    driver = webdriver.Remote('http://%s:%s/wd/hub' % (host, port), desired_caps)  # IP地址是Appium中的监听地址\n  File \"D:\\daima\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 156, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\daima\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1618543409452, "stop": 1618543423810}], "start": 1618543409452, "stop": 1618543423872}