{"uuid": "0cbc9724-8c52-485f-b352-89f24f3212eb", "children": ["cc61e300-5426-4186-bf1b-5d71d1001a6c"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''D:\\\\ruanjian\\\\android SDK\\\\platform-tools\\\\adb.exe' -P 5037 -s 35987d7f shell pm install -g /data/local/tmp/appium_cache/3d97225b036c28750562ef8962defee6b1af19a4.apk' exited with code 1'; Stderr: ''; Code: '1'\n\n", "trace": "  File \"D:\\daima\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\daima\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\daima\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\Appium_AutoTest-Mobile\\testcase\\conftest.py\", line 45, in start_appium_desired\n    driver = appium_desired_caps(host, port)\n  File \"D:\\Appium_AutoTest-Mobile\\base\\DesireCaps.py\", line 41, in appium_desired_caps\n    driver = webdriver.Remote('http://%s:%s/wd/hub' % (host, port), desired_caps)  # IP地址是Appium中的监听地址\n  File \"D:\\daima\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 156, in __init__\n    AppiumConnection(command_executor, keep_alive=keep_alive), desired_capabilities, browser_profile, proxy\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\daima\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\daima\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1618481772862, "stop": 1618481782057}], "start": 1618481772862, "stop": 1618481782120}